[package]
name = "cheddar-big-tic-tac-toe"
version = "1.0.0"
authors = ["guacharo", "robert-zaremba"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk.workspace = true
near-contract-standards.workspace = true
