[package]
name = "cheddar-big-tic-tac-toe"
version = "1.0.0"
authors = ["guacharo", "robert-zaremba"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.1.0"
near-contract-standards = "4.1.0"
serde_json = "1.0"
